#ddev-generated
services:
  redis:
    container_name: ddev-${DDEV_SITENAME}-redis
    build:
      args:
        BASE_IMAGE: redis:7.0.12-alpine3.18
      context: ".redisimageBuild"
      dockerfile: Dockerfile
      no_cache: true
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - type: "volume"
        source: redis
        target: "/data"
        volume:
          nocopy: true
      - ".:/mnt/ddev_config"
      - "./redis/conf:/usr/local/etc/redis/conf"
    command:
      - redis-server
      - /usr/local/etc/redis/conf/redis.conf

volumes:
  redis:
    name: ddev-${DDEV_SITENAME}-redis
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
