#ddev-generated
version: '3.6'
services:
  redis:
    container_name: ddev-${DDEV_SITENAME}-redis
    image: redis:7
    # These labels ensure this service is discoverable by ddev.
    user: "1000:1000"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
    - ".:/mnt/ddev_config"
    - "./redis/data:/data"
    - "./redis/conf:/usr/local/etc/redis/conf"
    command: ["redis-server", "/usr/local/etc/redis/conf/redis.conf"]
