name: "Daily tests"
on:
  schedule:
    - cron: "25 08 * * *"

jobs:
  run_tests:
    name: Run tests
    uses: oblakstudio/ddev-redis-7/.github/workflows/reusable_test_ddev_addon.yml@master
    with:
      ddev_version: '["stable", "HEAD", "edge"]'
      test_type: "release"
