name: E2E Tests
on:
  pull_request:
  merge_group:
  push:
    branches: [master]
    paths-ignore:
      - ".github/**/*"

  schedule:
    - cron: "25 08 * * *"

  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: Debug with tmate
        required: false
        default: false

  # This is required for "gautamkrishnar/keepalive-workflow"
permissions:
  contents: write

defaults:
  run:
    shell: bash

env:
  # NIGHTLY_DDEV_PR_URL: "https://nightly.link/ddev/ddev/actions/runs/1720215802/ddev-linux-amd64.zip"
  # Allow ddev get to use a github token to prevent rate limiting by tests
  DDEV_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Allow `--HEAD` flag when running tests against HEAD

jobs:
  test_stable:
    name: Test DDEV stable
    timeout-minutes: 5
    defaults:
      run:
        shell: bash
    runs-on: ddev-test-runner
    steps:
      - uses: actions/checkout@v3

      - name: tmate debugging session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
        if: github.event.inputs.debug_enabled == 'true'

      - name: Run BATS
        run: bats tests

      # keepalive-workflow adds a dummy commit if there's no other action here, keeps
      # GitHub from turning off tests after 60 days
      - uses: gautamkrishnar/keepalive-workflow@v1
        with:
          commit_message: "chore(workflow): Dummy commit [skip ci]"
